# Generated by Django 2.2.4 on 2019-12-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_auto_20191219_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
